### ISSUE TITLE
Random t/module.t failures

### ISSUE THREAD

**Issue by eserte** [gryphonshafer/Daemon-Device#3]
Sometimes the test suite fails like this:
```
# Failed test '2 children were appropriately replaced in under 10 seconds'
# at t/module.t line 84.
# Seeded srand with seed '20220319' from local date.
t/module.t ............... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/6 subtests 
```

**Comment by gryphonshafer** [comment]
I can't seem to reproduce this. What's the Perl version and OS these failures happen on? Also, what's the approximate system load when these failures happen? The test in question tries to kill off 2 children and watch for them to be replaced, so if the system is under high load, it's possible this can't be accomplished in 10 seconds.

**Comment by gryphonshafer** [comment]
I increased the wait iterations from 10 to 120 (roughly from 10 seconds to 120 seconds) in hopes that this addresses the problem.
